[tool.poetry]
name = "radas"
version = "1.0.0"
description = "Plasma radiation calculated using OpenADAS"
authors = ["Commonwealth Fusion Systems"]
readme = "README.md"

[tool.poetry.scripts]
radas = 'radas.cli:run_radas_cli'

[tool.poetry.dependencies]
python = "<3.12,>=3.9"
numpy = "^1.24.2"
scipy = "^1.11.2"
matplotlib = "^3.7.1"
Pint = "^0.23"
pyyaml = "^6.0"
xarray = "^2023.3.0"
pint-xarray = "^0.3"
click = "^8.1.3"
black = "^24.2.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
pytest-cov = "^4.1.0"
coverage = "^7.2.2"
ipykernel = "^6.22.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
addopts = "--cov=radas --cov-branch --cov-report term --cov-report xml:coverage.xml --import-mode=importlib"
pythonpath = [
  ".",
  "radas",
]
testpaths = [
  "tests",
]

[tool.coverage.run]
omit = [
  # These are built and executed at runtime. This is done in
  # a temporary repository. The temporary copies of the reader
  # are covered instead of the actual source files.
  "radas/readers/*"
]